# Changes here will be overwritten by Copier
_commit: v0.2.0
_src_path: gh:alan-turing-institute/python-project-template
coc: our_coc
email: adithya.r.devi@gmail.com
full_name: Adithya
license: MIT
min_python_version: '3.10'
org: adithyadevi3
project_name: CSCI-4050
project_short_description: ML project entailing a dataset
python_name: csci_4050
typing: loose
url: https://github.com/adithyadevi3/CSCI-4050
